langEn = {
  "dropdownNav" : "Sections",
  "cv" : "CV",
  "all" : "All",
  "repository" : " Repository",
  "professionalExperienceNav" : "Professional experience",
  "educationNav" : "Education",
  "certificationsNav" : "Certifications",
  "portfolioNav" : "Portfolio",
  "professionalExperience" : "PROFESSIONAL EXPERIENCE",
  "education" : "EDUCATION",
  "certifications" : "CERTIFICATIONS",
  "portfolio" : "PORTFOLIO",
  "rol" : "Developer",
  "resume" : "<p>My name is Aarón Socas Gaspar. I graduated in Computer Engineering from the University of La Laguna (Tenerife - Spain). I have focused my training in Information Technology, which has provided to me knowledge related with web and mobile development, security and data processing.</p>"
            +"<p>I consider myself as a hard worker person, active and dynamic. Be aware of the goals of the project I working for is important for me, It is helpful for me to be focussed and work hard. I am interested in continue learning and growing, and be part of interesting projects.</p>",
  "location" : "S/C de Tenerife. Spain",
  "email" : "Email",
  "linkedin" : "See my Linkedin",
  "github" : "Access to my repository",
  "car" : "Own vehicle",
  "proffesionalSkills" : "PROFFESIONAL SKILLS",
  "languages" : "LANGUAGES",
  "english" : "English",
  "spanish" : "Spanish",
  "otherKnowledge" : "OTHER KNOWLEDGE",
  "repositoryDevelopment" : "Collaborative development: Github y Bitbucket",
  "testMethods" : "Test methods: TDD and continuos integration",
  "testTools" : "Test tools: Selenium, Coveralls",
  "manageTools" : "Project manage: PivotalTracker, OpenProject",
  "agileMthodology" : "Agile methodology (Scrum)",
  "clouds" : "Clouds: PaaS (Heroku, OpenShift)",
  "database" : "SQL",
  "os" : "Linux and Windows",
  "coverLetterTitle" : "COVER LETTER",
  "coverLetter" : "<p>Dear Mr/Mrs:</p>"
              +"<p>My name is Aarón Socas Gaspar, Graduated in computer engineering in University of La Laguna (Tenerife - Spain). I decided to train me in technological field because it was always interesting for me as well as its applications and jobs.</p>"
              +"<p>I am working currecly for Atos in I+D+i (investigation, development and innovation) department, studying and developing modules related with security and privacy.</p>"
              +"<p>My profesional experience as developer have performed in INTEGRA Tecnología y Comunicación de Canarias Company. I also have  knowledge in system manage, I have a title job training in 2nd grade of Technical Higher Diploma in Systems and I was working in Chamber of Commerce in Santa Cruz de Tenerife as intern and University of La Laguna. I have oriented my training towards web technology, cloud development, content manager and security.</p>"
              +"<p>I am an active persion, curious, responsible, constant and perfectionist, with a great capacity of work and effort. I can adapt to different situations and changes and I can work in team or individually.</p>"
              +"<p>Kindest regards,</p>"
              +"<p>Aarón Socas Gaspar</p>"
              +"<p>https://alu0100207385.github.io/</p>",
  "printDocument" : "Print",
  "atosTime" : "2015/09/25 - Now",
  "atosRol" : "Researching, development and innovation (R&D+i)",
  "atosTasks" : "<p>I am working for R&D+i department and currently I am working in project related with security and privacy. I am developing an Android app for <a href='http://abc4eu.com/'>ABC4EU</a> project.</p>",
  "integraTime" : "2015/02/23 - 2015/05/07",
  "integraRol" : "Web developer",
  "integraTasks" : "<p>I collaborated in different projects in the development department. Mainly I dedicated to the development of applications and web design. I used tools like Laravel, Joomla and got experience in Scrum methodology.</p>",
  "laLagunaTime" : "2013/10/01 - 2015/06/30",
  "laLagunaRol" : "Systems technician / Intern",
  "laLagunaCompany": "University of La Laguna",
  "laLagunaTasks" : "<p>Maintenance tasks: installation and configuration of software and OS, cloning, cleaning, security, scripts, etc. I worked with desktops and other multimedia devices.</p>",
  "chamberOfCommerceTime" : "2007/04 - 2007/06",
  "chamberOfCommerceRol" : "Systems technician / Practices",
  "chamberOfCommerceCompany" : "Chamber of Commerce of Santa Cruz de Tenerife",
  "chamberOfCommerceTasks" : "<p>Installation, administration and configuration of equipment and development of improvements in the systems of the company. Management and maintenance of computer packages of general and specific purpose used in the company.</p>",
  "educationLaLagunaTime" : "2012/09/10 - 2015/09/22",
  "educationLaLagunaCareer" : "Graduated in Computer Engineering",
  "educationLaLagunaDetails" : "<p>Itinerary: Information Technologies: Web systems and technologies, IT and knowledge management of organizations, security and networks.</p>",
  "educationCesarManriqueTime" : "2005/09 - 2007/07",
  "educationCesarManriqueRol" : "Computer Systems Technician",
  "educationCesarManriqueCompany" : "IES Cesar Manrique",
  "educationCesarManriqueDetails" : "<p>Deploy and manage computer systems, network management, software installation and changes to improve system and application exploitation.</p>",
  "googleActivateDetails" : "A platform born with the aim of helping young people to have easier access not only to knowledge but also to training, entrepreneurship and the professional world.",
  "googleActivateMobileCourse" : "Mobile Apps Development course",
  "googleActivateMobileEmisor" : "Complutense University of Madrid",
  "googleActivateMobileDetails" : "Essential principles for the creation, design and programming of mobile applications.",
  "googleActivateWebCourse" : "Introduction to Web Development course (1)",
  "googleActivateWebEmisor" : "Institute of International Economics",
  "googleActivateWebDetails" : "Introduction to web design. History of the Web and creation of correct web pages with HTML5.",
  "googleActivateCloudCourse" : "Cloud Computing course",
  "googleActivateCloudEmisor" : "School of Industrial Organization",
  "googleActivateCloudDetails" : "Possibilities offered by the Cloud world to business. How to innovate to adapt to new technologies. Access to information from any device and securely.",
  "googleActivateECommerceCourse": "E-Commerce course",
  "googleActivateECommerceEmisor": "School of Industrial Organization",
  "googleActivateECommerceDetails": "Introduction and tools to know how to buy and sell products and services in the net.",
  "iterCourse" : "Center for Excellence in Development and Innovation (CEDEeI)",
  "iterCompany" : "Technological and Renewable Energy Institute",
  "iterDetails" : "At present, ITER is an international research center of reference in renewable energy, engineering, telecommunications and the environment. Here I learned different technologies, Java and Android among others.",
  "codeSchoolDetails" : "Code School is an online learning destination for existing and aspiring developers that teaches through entertaining content. Each course is built around a creative theme and storyline so that it feels like you’re playing a game, not sitting in a classroom. We combine gaming mechanics with video instruction and in-browser coding challenges to make learning fun and memorable. With over 60 courses covering HTML/CSS, JavaScript, Ruby, Python, .NET, iOS, Git, databases, and more, Code School pairs experienced instructors with meticulously produced, high-quality content inspired by our community and network of members.",
  "rubyCourseDetails" : "Elements of basic building blocks in Ruby.",
  "angularCourseDetails" : "Angular allows your application to have an expanded HTML library. Learn to add to your HTML behavior and accelerate the responsiveness of the application.",
  "javascriptCourse1Details" : "An introduction to the basics of the JavaScript language. Build a base of JavaScript syntax and learn how to use values, variables and files.",
  "gitCourseDetails" : "Learn how to use Git by reviewing the basics of Git version control. Introductory course that was created with GitHub.",
  "sqlCourseDetails" : "Basic skills of manipulation in database used in the SQL programming language.",
  "jqueryCourseDetails" : "JQuery 2.0 basics, a JavaScript library, modify page elements and improve user interaction.",
  "portfolioTime" : "2017/03/19*",
  "portfolioLastUpdate" : "*Last update",
  "portfolioView" : "See portfolio",
  "portfolioDetails" : "Here you can find some of my projects, practices and works in which I have collaborated.",
  "getCv" : "Get CV",
  "myEmail" : "socasgaspar@gmail.com",
  "myLinkedin" : "https://www.linkedin.com/in/aaronsocasgaspar/",
  "myGithub" : "https://github.com/alu0100207385",
  "certificationsDetailsPrint" : "Visit http://alu0100207385.github.io/ for more details.",
  "porfolioAbc4euSummary" : "I collaborated with an EU project called <a href=\"http://abc4eu.com/\">ABC4EU</a>. "
  + "My task was developing an app for border guard to control travellers, verify and check "
  + "their electronic documents. App is not public but you can see "
  + "it though video demonstration in the following "
  + "<a href=\"https://www.youtube.com/channel/UCp4Cfh2A7q5EEa8yK7xQrJw\">link</a>."
};
