langEs = {
  "dropdownNav" : "Secciones",
  "cv" : "CV",
  "all" : "Todo",
  "repository" : " Repositorio",
  "professionalExperienceNav" : "Experiencia profesional",
  "educationNav" : "Educación",
  "certificationsNav" : "Certificaciones",
  "portfolioNav" : "Portafolio",
  "professionalExperience" : "EXPERIENCIA PROFESIONAL",
  "education" : "EDUCACIÓN",
  "certifications" : "CERTIFICACIONES",
  "portfolio" : "PORTAFOLIO",
  "rol" : "Desarrollador",
  "resume": "<p>Mi nombre es Aarón Socas Gaspar. Graduado en Ingeniería "
            +"Informática por la Universidad de La Laguna. He orientado mi "
            +"formación en el uso de tecnologías de la información, la cual "
            +"engloba conocimientos relacionados con programación web y "
            +"dispositivos móviles, seguridad y tratamiento de la información.</p>"
            +"<p>Me considero una persona trabajadora, activa y dinámica. Doy importancia al objetivo del proyecto y esto me hace esforzarme más en mi trabajo. Quiero seguir aprendiendo y colaborar en proyectos interesantes.</p>",
  "location": "S/C de Tenerife. España",
  "email" : "Email",
  "linkedin" : "Ver mi Linkedin",
  "github" : "Accede a mi repositorio",
  "car" : "Vehículo propio",
  "proffesionalSkills" : "HABILIDADES PROFESIONALES",
  "languages" : "IDIOMAS",
  "english" : "Inglés",
  "spanish" : "Español",
  "otherKnowledge" : "OTROS CONOCIMIENTOS",
  "repositoryDevelopment" : "Desarrollo colaborativo: Github y Bitbucket",
  "testMethods" : "Métodos de pruebas: TDD e integración continua",
  "testTools" : "Herramientas de pruebas: Selenium, Coveralls",
  "manageTools" : "Gestión de proyectos: PivotalTracker, OpenProject",
  "agileMthodology" : "Metodologías ágiles (Scrum)",
  "clouds" : "Clouds: PaaS (Heroku, OpenShift)",
  "database" : "SQL",
  "os" : "SO Linux y Windows",
  "coverLetterTitle" : "CARTA DE PRESENTACIÓN",
  "coverLetter" : "<p>Estimado Sr/Sra:</p>"
                  +"<p>Mi nombre es Aarón Socas Gaspar, soy Graduado en Ingeniería Informática por la ULL. Decidí formarme en el ámbito tecnológico porque siempre me llamó la atención así como sus aplicaciones y salida laboral."
                  +"<p>Actualmente estoy trabajando para Atos dentro del departamento de I+D+i, investigando y desarrollando módulos relacionados con la seguridad y privacidad.</p>"
                  +"<p>Mi experiencia profesional como desarrollador la he realizado en la empresa INTEGRA Tecnología y Comunicación de Canarias, SL. También poseo conocimientos en administración de sistemas, tengo el título de formación profesional 2º grado de Diplomado Técnico Superior en Sistemas y estuve como becario en la Cámara de Comercio de Santa Cruz de Tenerife y en la Universidad de La Laguna. He orientado mi formación hacia la tecnología web, desarrollo en la nube, gestión de contenidos y seguridad.</p>"
                  +"<p>Soy una persona activa, curiosa. responsable, constante y perfeccionista, con una gran capacidad de trabajo y esfuerzo. Soy capaz de adaptarme a las distintas situaciones y a los cambios, pudiendo trabajar de forma efectiva en equipo o individual.</p>"
                  +"<p>Un cordial saludo,</p>"
                  +"<p>Aarón Socas Gaspar</p>"
                  +"<p>https://alu0100207385.github.io/</p>",
  "printDocument" : "Imprimir",
  "atosTime" : "25/09/2015 - Actualmente",
  "atosRol" : "Investigación, desarrollo e innovación(I+D+i)",
  "atosTasks" : "<p>Estoy asignado en el departamento de I+D+i, actualmente trabajando en proyectos relacionados con la seguridad, privacidad y criptografía. Estoy desarrollando una app Android para el proyecto <a href='http://abc4eu.com/'>ABC4EU</a>.</p>",
  "integraTime" : "23/02/2015 - 07/05/2015",
  "integraRol" : "Programador web",
  "integraTasks" : "<p>Colaboré en distintos proyectos en el departamento de desarrollo. Principalmente me dediqué al desarrollo de aplicaciones y diseño web. Utilicé herramientas como Laravel, Joomla y adquirí experiencia práctica en la metodología scrum.</p>",
  "laLagunaTime" : "01/10/2013 - 30/06/2015",
  "laLagunaRol" : "Técnico de sistemas / Becario",
  "laLagunaCompany": "Universidad de La Laguna",
  "laLagunaTasks" : "<p>Tareas de mantenimiento: instalaciones y configuración de software y SO, clonaciones, limpieza, seguridad, scripts, etc. Trabajo con equipos de mesa y otros dispositivos multimedia.</p>",
  "chamberOfCommerceTime" : "04/2007 - 06/2007",
  "chamberOfCommerceRol" : "Técnico de sistemas / Prácticas",
  "chamberOfCommerceCompany" : "Cámara de Comercio de Santa Cruz de Tenerife",
  "chamberOfCommerceTasks" : "<p>Instalación, administración y configuración de equipos y desarrollo de mejoras en los sistemas de la empresa. Manejo y mantenimiento de los paquetes informáticos de propósito general y específico utilizados en la empresa.</p>",
  "educationLaLagunaTime" : "10/09/2012 - 22/09/2015",
  "educationLaLagunaCareer" : "Grado en Ingeniería Informática",
  "educationLaLagunaDetails" : "<p>Itinerario: Tecnologías de la Información: Sistemas y tecnologías web, TI y gestión del conocimiento de las organizaciones, seguridad y redes.</p>",
  "educationCesarManriqueTime" : "09/2005 - 07/2007",
  "educationCesarManriqueRol" : "Técnico superior de sistemas informáticos",
  "educationCesarManriqueCompany" : "IES Cesar Manrique",
  "educationCesarManriqueDetails" : "<p>Implantar y administrar sistemas informáticos, gestión de redes, instalación de software y cambios para mejorar la explotación del sistema y las aplicaciones</p>.",
  "googleActivateDetails" : "Una plataforma que nace con el objetivo de ayudar a los jóvenes a que tengan un más fácil acceso no solo al conocimiento sino también a la formación, al emprendimiento y al mundo profesional.",
  "googleActivateMobileCourse" : "Curso de Desarrollo de Apps Móviles",
  "googleActivateMobileEmisor" : "Universidad Complutense de Madrid",
  "googleActivateMobileDetails" : "Principios esenciales para la creación, diseño y programación de aplicaciones móviles.",
  "googleActivateWebCourse" : "Curso de Introducción al Desarrollo Web (1)",
  "googleActivateWebEmisor" : "Instituto de Economía Internacional",
  "googleActivateWebDetails" : "Introducción al diseño web. Historia de la Web y creación de páginas web correctas con HTML5.",
  "googleActivateCloudCourse" : "Curso de computación en la nube",
  "googleActivateCloudEmisor" : "Escuela de Organización Industrial",
  "googleActivateCloudDetails" : "Posibilidades que ofrece el mundo Cloud a los negocios. Cómo innovar para adaptarse las nuevas tecnologías. Acceso a la información desde cualquier dispositivo y de forma segura.",
  "googleActivateECommerceCourse": "Curso de comercio electrónico",
  "googleActivateECommerceEmisor": "Escuela de organización industrial",
  "googleActivateECommerceDetails": "Introducción al comercio electrónico y sus herramientas para saber cómo comprar y vender productos y servicios en la red.",
  "iterCourse" : "Centro de Excelencia de Desarrollo e Innovación (CEDEeI)",
  "iterCompany" : "Instituto Tecnológico y de Energías Renovables",
  "iterDetails" : "En la actualidad, el ITER es un centro de investigación de referencia internacional en energías renovables, ingeniería, telecomunicaciones y medio ambiente. Aquí aprendí distintas tecnologías, Java y Android entre otras.",
  "codeSchoolDetails" : "Code School es un portal online dirigido a desarrolladores que enseña a través de contenidos de entretenimiento. Con más de 50 cursos (Ruby, JavaScript, HTML/CSS, iOS, Git, bases de datos, etc.) Code School junta experimentados instructores con un contenido atractivo y de alta calidad inspirado para su comunidad. Más de 1 millón de personas en todo el mundo visita Code School para mejorar sus habilidades de desarrollo y aprender sobre la marcha.",
  "rubyCourseDetails" : "Elementos de bloques de construcción básicos en Ruby.",
  "angularCourseDetails" : "Angular permite que su aplicación tenga una biblioteca de HTML ampliado. Aprender a sumar a su comportamiento HTML y acelerar la capacidad de respuesta de la aplicación.",
  "javascriptCourse1Details" : "Una introducción a los conceptos básicos del lenguaje JavaScript. Construir una base de la sintaxis de JavaScript y aprender a utilizar los valores, variables y archivos.",
  "gitCourseDetails" : "Aprende a usar Git mediante la revisión de los conceptos básicos de control de versiones Git. Curso de introducción que se creó con GitHub.",
  "sqlCourseDetails" : "Lecciones de habilidades básicas de manipulación en base de datos utilizado en el lenguaje de programación SQL.",
  "jqueryCourseDetails" : "Conceptos básicos de jQuery 2.0, una biblioteca JavaScript, modificar elementos de la página y mejorar la interacción del usuario.",
  "portfolioTime" : "19/03/2017*",
  "portfolioLastUpdate" : "*Última actualización",
  "portfolioView" : "Ver portafolio",
  "portfolioDetails" : "Aquí podrás encontrar algunos de mis proyectos, prácticas y trabajos en los que he colaborado.",
  "getCv" : "Obtener CV",
  "myEmail" : "socasgaspar@gmail.com",
  "myLinkedin" : "https://www.linkedin.com/in/aaronsocasgaspar/",
  "myGithub" : "https://github.com/alu0100207385",
  "certificationsDetailsPrint" : "Visita http://alu0100207385.github.io/ para más detalles."
};

